language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install --server=http://luarocks.org/dev openssl
  - luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - luarocks install busted
  - luarocks install rapidjson 0.4.5-1
  - luarocks install luacrypto 0.3.2-2
  - luarocks install date 2.1.2-1

script:
  - busted spec

notifications:
  email:
    on_success: change
    on_failure: always
